# Generated by Django 6.1.1 on 2026-10-06 09:26

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntreprisesApp', '0001_initial'),
        ('ExpeditionsApp', '0001_initial'),
        ('OffresApp', '0001_initial'),
        ('VehiculesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='delai_jours',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='offre',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='offre',
            name='statut',
            field=models.CharField(choices=[('proposee', 'Proposee'), ('acceptee', 'Acceptee'), ('refusee', 'Refusee'), ('retiree', 'Retiree')], default='proposee', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='offre',
            constraint=models.CheckConstraint(condition=models.Q(('prix__gt', 0)), name='offre_prix_positif'),
        ),
        migrations.AddConstraint(
            model_name='offre',
            constraint=models.CheckConstraint(condition=models.Q(('delai_jours__gte', 1)), name='offre_delai_min_1'),
        ),
    ]
