# Generated by Django 6.1.1 on 2026-10-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntreprisesApp', '0001_initial'),
        ('ExpeditionsApp', '0002_alter_expedition_entreprise_and_more'),
        ('OffresApp', '0002_alter_offre_delai_jours_alter_offre_prix_and_more'),
        ('VehiculesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='offre',
            constraint=models.UniqueConstraint(condition=models.Q(('statut', 'proposee')), fields=('expedition', 'transporteur'), name='offre_une_proposee_par_transporteur_et_expedition', violation_error_message='Cette entreprise a deja une offre proposee sur cette expedition.'),
        ),
    ]
