# Generated by Django 6.1.1 on 2026-10-06 09:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EntreprisesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=20, unique=True)),
                ('type_vehicule', models.CharField(choices=[('camionnette', 'Camionnette'), ('fourgon', 'Fourgon'), ('camion_porteur', 'Camion porteur'), ('semi_remorque', 'Semi-remorque')], max_length=20)),
                ('capacite_kg', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('disponible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entreprise', models.ForeignKey(limit_choices_to={'type_entreprise': 'transporteur'}, on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to='EntreprisesApp.entreprise')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('capacite_kg__gt', 0)), name='vehicule_capacite_kg_positive')],
            },
        ),
    ]
