# Generated by Django 6.1.1 on 2026-10-06 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EntreprisesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=20, unique=True)),
                ('ville_depart', models.CharField()),
                ('ville_arrivee', models.CharField()),
                ('poids_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_souhaitee', models.DateField()),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('publiee', 'publiee'), ('attribuee', 'attribuee'), ('en_cours', 'en_cours'), ('livree', 'livree'), ('annulee', 'annulee')], default='publiee', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedition', to='EntreprisesApp.entreprise')),
            ],
        ),
    ]
