# Generated by Django 6.1.1 on 2026-10-05 21:31

import ExpeditionsApp.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("EntreprisesApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expedition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        default=ExpeditionsApp.models.generer_reference,
                        editable=False,
                        max_length=12,
                        unique=True,
                    ),
                ),
                ("ville_depart", models.CharField(max_length=100)),
                ("ville_arrivee", models.CharField(max_length=100)),
                ("poids_kg", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_souhaitee", models.DateField()),
                ("description", models.TextField(blank=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("publiee", "Publiée"),
                            ("attribuee", "Attribuée"),
                            ("en_cours", "En cours"),
                            ("livree", "Livrée"),
                            ("annulee", "Annulée"),
                        ],
                        default="publiee",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entreprise",
                    models.ForeignKey(
                        limit_choices_to={"type_entreprise": "chargeur"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expeditions",
                        to="EntreprisesApp.entreprise",
                    ),
                ),
            ],
        ),
    ]
