# Generated by Django 6.1.1 on 2026-10-06 10:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntreprisesApp', '0001_initial'),
        ('ExpeditionsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedition',
            name='entreprise',
            field=models.ForeignKey(limit_choices_to={'type_entreprise': 'chargeur'}, on_delete=django.db.models.deletion.CASCADE, related_name='expedition', to='EntreprisesApp.entreprise'),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='poids_kg',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='reference',
            field=models.CharField(editable=False, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='La reference doit suivre le format EXP-AA-NNNNN.', regex='^EXP-\\d{2}-\\d{5}$')]),
        ),
        migrations.AddConstraint(
            model_name='expedition',
            constraint=models.CheckConstraint(condition=models.Q(('poids_kg__gt', 0)), name='expedition_poids_kg_positif'),
        ),
    ]
